import type { Metadata } from "next";
import { Inter, Montserrat, Geist, Geist_Mono, Barlow, Barlow_Condensed, Ranga, DM_Serif_Display } from "next/font/google";
import "./globals.css";
import Script from 'next/script';
import Footer from "@liderexperto/components/Footer";
import { Suspense } from "react";
import MetaPixelEvents from "@liderexperto/components/MetaPixelEvents"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Ajusta los pesos
  display: "swap",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat", // Variable CSS para Montserrat
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Especifica todos los pesos que necesitas
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

const barlow = Barlow({
  subsets: ["latin"],
  variable: "--font-barlow",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Ajusta los pesos según necesites
  display: "swap",
});

const barlowCondensed = Barlow_Condensed({
  subsets: ['latin'],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: '--font-barlow-condensed',
  display: "swap",
});

const ranga = Ranga({
  subsets: ['latin'],
  weight: ["400", "700"],
  variable: '--font-ranga',
  display: "swap",
});

const dmSerif = DM_Serif_Display({
  weight: '400', // o 'italic' si deseas también
  subsets: ['latin'],
  variable: '--font-dm-serif',
});


export const metadata: Metadata = {
  title: "Lider Experto - Hugo Coach",
  description: "Generated by create next app",
  // Agregar estas configuraciones de seguridad
  other: {
    'referrer': 'origin',
    'Content-Security-Policy': "upgrade-insecure-requests; default-src 'self' https: data: 'unsafe-inline' 'unsafe-eval';"
  }
};

const META_PIXEL_ID = 1449506382718655;


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="referrer" content="origin" />
        <meta httpEquiv="Content-Security-Policy" content="upgrade-insecure-requests" />

        <Script
          id="meta-pixel-base"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              !function(f,b,e,v,n,t,s)
              {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
              n.callMethod.apply(n,arguments):n.queue.push(arguments)};
              if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
              n.queue=[];t=b.createElement(e);t.async=!0;
              t.src=v;s=b.getElementsByTagName(e)[0];
              s.parentNode.insertBefore(t,s)}(window, document,'script',
              'https://connect.facebook.net/en_US/fbevents.js');
              fbq('init', '${META_PIXEL_ID}');
              console.log('Meta Pixel initialized with ID:', '${META_PIXEL_ID}');
            `.replace(/\$\{META_PIXEL_ID\}/g, META_PIXEL_ID.toString()),
          }}
        />

        <Script
          id="google-tag-manager"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
              new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
              j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
              'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
              })(window,document,'script','dataLayer','GTM-M26GH75L'); // 
            `,
          }}
        />

        {/* Google tag (gtag.js) - Script externo */}
        <Script
          id="google-gtag-external" // ID único para este script
          strategy="afterInteractive" // Carga después de que la página sea interactiva
          src="https://www.googletagmanager.com/gtag/js?id=G-WCW3MV8KDB"
          async // El atributo async es importante para este script
        />
        {/* Google tag (gtag.js) - Script de inicialización en línea */}
        <Script
          id="google-gtag-init" // ID único para este script
          strategy="afterInteractive" // Carga después de que la página sea interactiva
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-WCW3MV8KDB');
            `,
          }}
        />
        {/* Fin Google tag (gtag.js) */}


        <Script src="https://cdn.brevo.com/js/sdk-loader.js" async />
        <Script id="brevo-init" strategy="lazyOnload">
          {`
              // Version: 2.0
              window.Brevo = window.Brevo || [];
              Brevo.push([
                  "init",
                  { client_key: "07eiu4pstz0wiy4djwvb1pn0" }
              ]);
            `}
        </Script>
      </head>
      <body
        className={`${inter.variable} ${montserrat.variable} ${geistSans.variable} ${geistMono.variable} ${barlow.variable} ${barlowCondensed.variable} ${ranga.variable} ${dmSerif.variable} font-sans antialiased`}
      >
        {/* Google Tag Manager (noscript) - Colócalo inmediatamente después de la etiqueta <body> de apertura */}
        <noscript
          dangerouslySetInnerHTML={{
            __html: `<iframe src="https://www.googletagmanager.com/ns.html?id=GTM-M26GH75L"
            height="0" width="0" style="display:none;visibility:hidden"></iframe>`,
          }}
        />
        {/* Fin Google Tag Manager (noscript) */}
        

        <div className="flex flex-col max-w-[100%] min-h-[100dvh]">
          <main>
            {children}
          </main>

          <Footer />
        </div>
        
        <Suspense fallback={null}>
          <MetaPixelEvents /> 
        </Suspense>
      </body>
    </html>
  );
}
